### ISSUE TITLE
StringIndexOutOfBoundsException tipying only the "space"

### ISSUE THREAD

**Issue by slumdroid** [vishnus/Olam#1]
E/AndroidRuntime(  727): FATAL EXCEPTION: AsyncTask #1
E/AndroidRuntime(  727): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime(  727):    at android.os.AsyncTask$3.done(AsyncTask.java:299)
E/AndroidRuntime(  727):    at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
E/AndroidRuntime(  727):    at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
E/AndroidRuntime(  727):    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
E/AndroidRuntime(  727):    at java.util.concurrent.FutureTask.run(FutureTask.java:137)
E/AndroidRuntime(  727):    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
E/AndroidRuntime(  727):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
E/AndroidRuntime(  727):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
E/AndroidRuntime(  727):    at java.lang.Thread.run(Thread.java:856)
E/AndroidRuntime(  727): Caused by: java.lang.StringIndexOutOfBoundsException: length=0; index=-1
E/AndroidRuntime(  727):    at com.olam.PorterStemmerAlgo.step1(PorterStemmerAlgo.java:171)
E/AndroidRuntime(  727):    at com.olam.Stemmer.completeStem(Stemmer.java:21)
E/AndroidRuntime(  727):    at com.olam.MainSearch$doSearch.doInBackground(MainSearch.java:253)
E/AndroidRuntime(  727):    at com.olam.MainSearch$doSearch.doInBackground(MainSearch.java:228)
E/AndroidRuntime(  727):    at android.os.AsyncTask$2.call(AsyncTask.java:287)
E/AndroidRuntime(  727):    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
E/AndroidRuntime(  727):    ... 5 more

**Comment by tapanprakasht** [comment]
Please close this issue. This issue is reproducible only in Play store version. I think the issue has been fixed in the current repository.
