### ISSUE TITLE
Force Close when enter word with apostrophe

### ISSUE THREAD

**Issue by slumdroid** [vishnus/Olam#2]
E/AndroidRuntime(  727): FATAL EXCEPTION: AsyncTask #1
E/AndroidRuntime(  727): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime(  727):    at android.os.AsyncTask$3.done(AsyncTask.java:299)
E/AndroidRuntime(  727):    at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
E/AndroidRuntime(  727):    at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
E/AndroidRuntime(  727):    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
E/AndroidRuntime(  727):    at java.util.concurrent.FutureTask.run(FutureTask.java:137)
E/AndroidRuntime(  727):    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
E/AndroidRuntime(  727):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
E/AndroidRuntime(  727):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
E/AndroidRuntime(  727):    at java.lang.Thread.run(Thread.java:856)
E/AndroidRuntime(  727): Caused by: android.database.sqlite.SQLiteException: near "s": syntax error (code 1): , while compiling: SELECT word, _id FROM words_en WHERE stems LIKE '%slumdroid's test %' OR stems LIKE 'slumdroid's test' ORDER BY LENGTH(word) LIMIT 10
E/AndroidRuntime(  727):    at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
E/AndroidRuntime(  727):    at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:882)
E/AndroidRuntime(  727):    at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:493)
E/AndroidRuntime(  727):    at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
E/AndroidRuntime(  727):    at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
E/AndroidRuntime(  727):    at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
E/AndroidRuntime(  727):    at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
E/AndroidRuntime(  727):    at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1314)
E/AndroidRuntime(  727):    at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1253)
E/AndroidRuntime(  727):    at com.olam.DatabaseHelper.getSimilarStems(DatabaseHelper.java:115)
E/AndroidRuntime(  727):    at com.olam.MainSearch$doSearch.doInBackground(MainSearch.java:255)
E/AndroidRuntime(  727):    at com.olam.MainSearch$doSearch.doInBackground(MainSearch.java:228)
E/AndroidRuntime(  727):    at android.os.AsyncTask$2.call(AsyncTask.java:287)
E/AndroidRuntime(  727):    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
E/AndroidRuntime(  727):    ... 5 more

**Comment by tapanprakasht** [comment]
Please close this issue. This issue is reproducible only in Play store version. I think the issue has been fixed in the current repository.
